---
dependencies:
- name: postgresql
  version: 13.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 18.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled  