nginx-ingress:
  enabled: true
  controller:
    publishService:
      enabled: true
gateway:
  name: xebula-api-gateway
  image: enesserol7/xebula-api-gateway
  imageTag: 9bb62f1

rabbitmq:
  auth:
    enabled: true
    username: yourUsername
    password: yourPassword
    
postgresql:

  image:
    repository: bitnami/postgresql
  ## Use the PostgreSQL chart dependency.
  ##
  enabled: true

  ### PostgreSQL User to create.
  ##
  postgresqlUsername: postgres

  ## PostgreSQL Password for the new user.
  ## If not set, a random 10 characters password will be used.
  ##
  # postgresqlPassword: 

  ## PostgreSQL Database to create.
  ##
  postgresqlDatabase: xebula
  

  ## PostgreSQL service port
  primary:
    extraEnvVars:
    - name: POSTGRES_USER
      value: xebula

    - name: POSTGRES_DB
      value: xebula  
    service:
      ports:
        postgresql: 5432

  ## Persistent Volume Storage configuration for PostgreSQL.
  ##
  ## Ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  ##
  persistence:
    ## Enable PostgreSQL persistence using Persistent Volume Claims.
    ##
    enabled: true

    ## Persistent Volume Storage Class to be used by PersistentVolumes created
    ## for PostgreSQL.
    ##
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass:

    ## Persistent Volume Access Mode.
    ##
    accessModes:
      - ReadWriteOnce

    ## Persistent Volume Storage Size.
    ##
    size: 2Gi  

redis:
  ## Use the redis chart dependency.
  ##
  enabled: true

  redisPort: 6379

  master:
    persistence:
      enabled: true
      storageClass:
      accessModes:
        - ReadWriteOnce
      size: 1Gi

  ##
  ## Disable cluster management by default.
  cluster:
    enabled: false    

mongodb:
  ## Use the MongoDB chart dependency.
  ##
  enabled: true

  ## MongoDB root user password
  ##

  ## MongoDB database to create
  ##
  mongodbDatabase: yourDatabaseName

  ## MongoDB service port
  service:
    port: 27017

  ## Persistent Volume Storage configuration for MongoDB
  ##
  ## Ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  ##
  persistence:
    ## Enable MongoDB persistence using Persistent Volume Claims.
    ##
    enabled: true

    ## Persistent Volume Storage Class to be used by PersistentVolumes created
    ## for MongoDB.
    ##
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ## set, choosing the default provisioner. (gp2 on AWS, standard on GKE, AWS & OpenStack)
    ##
    storageClass:

    ## Persistent Volume Access Mode.
    ##
    accessModes:
      - ReadWriteOnce

    ## Persistent Volume Storage Size.
    ##
    size: 2Gi