apiVersion: apps/v1
kind: Deployment
metadata:
  name: xebula-content-service
  labels:
    app: xebula-content-service
spec:
  selector:
    matchLabels:
      app: xebula-content-service
  replicas: 1
  template:
    metadata:
      labels:
        app: xebula-content-service
    spec:
      containers:
        - name: xebula-content-service
          image: enesserol7/xebula-content-service:2706666
          ports:
            - containerPort: 80
              name: api-http
          env:
            - name: CORS_ALLOWORIGIN
              value: https://dev.xebula.io
            - name: DATABASE_IP
              value: xebula-postgresql.default.svc.cluster.local
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: xebula
            - name: DATABASE_SSLMODE
              value: disable
            - name: DATABASE_MAXIDLE
              value: "30"
            - name: DATABASE_MAXOPEN
              value: "30"
            - name: DATABASE_MAXLIFETIME
              value: "60"
            - name: DATABASE_USER
              value: xebula
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: xebula-postgresql
            - name: REDIS_HOST
              value: xebula-redis-master.default.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_SCHEME
              value: rediss
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: xebula-redis
            - name: MONGO_PROTOCOL
              value: mongodb
            - name: MONGO_USER
              value: root
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongodb-root-password
                  name: xebula-mongodb
            - name: MONGO_HOST
              value: xebula-mongodb.default.svc.cluster.local
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: xebula
            - name: MONGO_OPTIONS
              value:
            - name: SERVER_PORT
              value: "80"
      imagePullSecrets:
        - name: regcred
