apiVersion: apps/v1
kind: Deployment
metadata:
  name: xebula-crypto-service
  labels:
    app: xebula-crypto-service
spec:
  selector:
    matchLabels:
      app: xebula-crypto-service
  replicas: 1
  template:
    metadata:
      labels:
        app: xebula-crypto-service
    spec:
      containers:
        - name: xebula-crypto-service
          image: enesserol7/xebula-crypto-service:a29c372
          ports:
            - containerPort: 80
              name: api-http
          env:
            - name: CORS_ALLOWORIGIN
              value: https://dev.xebula.io
            - name: DATABASE_IP
              value: postgresdb
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: xebula
            - name: DATABASE_SSLMODE
              value: disable
            - name: DATABASE_MAXIDLE
              value: "30"
            - name: DATABASE_MAXOPEN
              value: "30"
            - name: DATABASE_MAXLIFETIME
              value: "60"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: do-pgsql
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: do-pgsql
            - name: MONGO_PROTOCOL
              value: mongodb
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_ROOT_USERNAME
                  name: mongodb-secret
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_ROOT_PASSWORD
                  name: mongodb-secret
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: xebula
            - name: MONGO_OPTIONS
            - name: REDIS_HOST
              value: redis.redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_SCHEME
              value: redis
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: do-redis
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: rabbitmq
            - name: RABBIT_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: rabbitmq
            - name: RABBIT_SCHEME
              valueFrom:
                secretKeyRef:
                  key: scheme
                  name: rabbitmq
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: rabbitmq
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rabbitmq
            - name: LOGSTASH_HOST
              value: logstash-svc.elk-stack
            - name: LOGSTASH_PORT
              value: "5000"
            - name: WALLETAPI_HOST
              value: xebula-wallet-api.default.svc.cluster.local
            - name: WALLETAPI_PORT
              value: "9000"
            - name: BALANCESERVICE_HOST
              value: xebula-balance-service.default.svc.cluster.local
            - name: BALANCESERVICE_PORT
              value: "9000"
            - name: FEEDSERVICE_HOST
              value: xebula-feed-service.default.svc.cluster.local
            - name: FEEDSERVICE_PORT
              value: "9000"
      imagePullSecrets:
        - name: regcred
