apiVersion: batch/v1
kind: Job
metadata:
  name: xebula-keycloak-secrets
spec:
  template:
    spec:
      containers:
      - name: xebula-keycloak-secrets
        image: enesserol7/xebula-keycloak-secrets:f9dd2dd
        imagePullPolicy: Always
      restartPolicy: Never