apiVersion: apps/v1
kind: Deployment
metadata:
  name: xebula-keycloak
spec:
  selector:
    matchLabels:
      app: xebula-keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: xebula-keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: postgresdb
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: xebula
            - name: KC_DB_SCHEMA
              value: keycloak
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: do-pgsql
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: do-pgsql
      imagePullSecrets:
        - name: regcred
