apiVersion: v1
kind: Service
metadata:
  labels:
    app: xebula-mpc-service
  name: xebula-mpc-service
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: xebula-mpc-service